baseURL = "https://ihux.cn"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "祀画の次元"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "Zeuk"

[blackfriday]
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "友链"
  weight = 40
  identifier = "link"
  url = "/link/"
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "念念不忘，必有回响！"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "My Home"                                          # site's footer slogan  # 网站页脚标语
  keywords = ["祀画", "Sihua","祀画の次元"]                                  # site's keywords  # 网站关键字
  description = "祀画の次元"                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

[social]
  github = " "
  twitter = " "
#  facebook = " "
  weibo = " "
#  instagram = " "